"""后端统一错误定义。"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class ErrorCode(str, Enum):
    """业务错误码集合。"""

    BOARD_DETECT_EMPTY = "BOARD_DETECT_EMPTY"
    BOARD_DETECT_AMBIGUOUS = "BOARD_DETECT_AMBIGUOUS"
    BOARD_DETECT_PERMISSION_DENIED = "BOARD_DETECT_PERMISSION_DENIED"
    BOARD_DETECT_SCAN_FAILED = "BOARD_DETECT_SCAN_FAILED"
    OFFICIAL_SOURCE_NOT_FOUND = "OFFICIAL_SOURCE_NOT_FOUND"
    OFFICIAL_SOURCE_UNREACHABLE = "OFFICIAL_SOURCE_UNREACHABLE"
    OFFICIAL_SOURCE_PARSE_FAILED = "OFFICIAL_SOURCE_PARSE_FAILED"
    SPEC_PARSE_FAILED = "SPEC_PARSE_FAILED"
    GEN_REQUIREMENT_INVALID = "GEN_REQUIREMENT_INVALID"
    GEN_TEMPLATE_NOT_SUPPORTED = "GEN_TEMPLATE_NOT_SUPPORTED"
    GEN_DEPENDENCY_RESOLVE_FAILED = "GEN_DEPENDENCY_RESOLVE_FAILED"
    FLASH_CONFIRMATION_REQUIRED = "FLASH_CONFIRMATION_REQUIRED"
    FLASH_TOOL_NOT_FOUND = "FLASH_TOOL_NOT_FOUND"
    FLASH_DEVICE_BUSY = "FLASH_DEVICE_BUSY"
    FLASH_FAILED = "FLASH_FAILED"
    RUN_CHECK_TIMEOUT = "RUN_CHECK_TIMEOUT"
    RUN_CHECK_NO_SIGNAL = "RUN_CHECK_NO_SIGNAL"
    RUN_CHECK_PROFILE_INVALID = "RUN_CHECK_PROFILE_INVALID"
    RUN_CHECK_PORT_OPEN_FAILED = "RUN_CHECK_PORT_OPEN_FAILED"
    RUN_CHECK_WRITE_FAILED = "RUN_CHECK_WRITE_FAILED"
    RUN_CHECK_KEYWORD_MISSING = "RUN_CHECK_KEYWORD_MISSING"
    FLASH_PLAN_UNSUPPORTED_BOARD = "FLASH_PLAN_UNSUPPORTED_BOARD"
    FLASH_PLAN_ARTIFACT_MISSING = "FLASH_PLAN_ARTIFACT_MISSING"
    FLASH_PLAN_TOOL_NOT_FOUND = "FLASH_PLAN_TOOL_NOT_FOUND"
    EVAL_BOARD_NOT_READY = "EVAL_BOARD_NOT_READY"
    EVAL_SCENARIO_INVALID = "EVAL_SCENARIO_INVALID"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    INTERNAL_FAILED = "INTERNAL_FAILED"


@dataclass
class AppException(Exception):
    """可映射到 HTTP 响应的业务异常。"""

    code: ErrorCode
    message: str
    status_code: int = 400

    def __str__(self) -> str:
        """返回可读错误信息。"""
        return f"{self.code.value}: {self.message}"
